name: Build

on:
  push:
  pull_request:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y cmake gcc-arm-none-eabi build-essential

      - name: Clone the Raspberry Pi Pico SDK
        run: |
          git clone --branch master --depth 1 https://github.com/raspberrypi/pico-sdk.git
          cd pico-sdk && git submodule update --init

      - name: Create build directory
        # We'll use this as our working directory for all subsequent commands
        run: cmake -E make_directory build

      - name: Configure CMake
        working-directory: build
        run: |
          export PICO_SDK_PATH=${{github.workspace}}/pico-sdk
          cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build the project
        working-directory: build
        # Execute the build. You can specify a specific target with "--target <NAME>"
        run: cmake --build . --parallel $(nproc)
